[package]
name = "ream-syntax"
description = "The lexer, parser, and syntax tree for Ream."

version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
dashu-int.workspace = true
emojis = "0.9.0"
rowan = "0.17.0"
unicode-segmentation = "1.13.3"

[lints]
workspace = true

[dev-dependencies]
similar-asserts = "2.0.0"
